import sys

with open("src/app/mod.rs", "r") as f:
    lines = f.readlines()

new_lines = []
for i, line in enumerate(lines):
    if "ActiveView::FilterConfig => {" in line:
        # Insert our new views before FilterConfig
        new_lines.extend([
            "                    ActiveView::UploadModeSelect => match key.code {\n",
            "                        crossterm::event::KeyCode::Char('s') | crossterm::event::KeyCode::Char('S') => {\n",
            "                            let _ = tx.try_send(AppEvent::UploadModeSelected(UploadMode::Select));\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Char('y') | crossterm::event::KeyCode::Char('Y') => {\n",
            "                            let _ = tx.try_send(AppEvent::UploadModeSelected(UploadMode::Sync));\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Esc => {\n",
            "                            self.active_view = ActiveView::Home;\n",
            "                        }\n",
            "                        _ => {}\n",
            "                    },\n",
            "                    ActiveView::UploadSyncResume => match key.code {\n",
            "                        crossterm::event::KeyCode::Char('y') | crossterm::event::KeyCode::Char('Y') | crossterm::event::KeyCode::Enter => {\n",
            "                            self.upload_dest_group_id = Some(self.upload_sync_state.as_ref().unwrap().dest_group_id);\n",
            "                            self.upload_dest_topic_id = self.upload_sync_state.as_ref().unwrap().dest_topic_id;\n",
            "                            // Filter out already uploaded files from selection\n",
            "                            if let Some(state) = &self.upload_sync_state {\n",
            "                                for (i, entry) in self.upload_entries.iter().enumerate() {\n",
            "                                    if let UploadEntry::File { name, size_bytes, .. } = entry {\n",
            "                                        if !state.uploaded_files.iter().any(|f| f.filename == *name && f.size_bytes >= *size_bytes) {\n",
            "                                            self.upload_selected[i] = true;\n",
            "                                        }\n",
            "                                    }\n",
            "                                }\n",
            "                            }\n",
            "                            self.active_view = ActiveView::UploadFileSelect;\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Char('n') | crossterm::event::KeyCode::Char('N') => {\n",
            "                            self.upload_sync_state = None;\n",
            "                            self.active_view = ActiveView::UploadFileSelect;\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Esc => {\n",
            "                            self.active_view = ActiveView::Home;\n",
            "                        }\n",
            "                        _ => {}\n",
            "                    },\n",
            "                    ActiveView::UploadFileSelect => match key.code {\n",
            "                        crossterm::event::KeyCode::Down | crossterm::event::KeyCode::Char('j') => {\n",
            "                            if !self.upload_entries.is_empty() {\n",
            "                                let i = match self.upload_list_state.selected() {\n",
            "                                    Some(i) => if i >= self.upload_entries.len() - 1 { i } else { i + 1 },\n",
            "                                    None => 0,\n",
            "                                };\n",
            "                                self.upload_list_state.select(Some(i));\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Up | crossterm::event::KeyCode::Char('k') => {\n",
            "                            if !self.upload_entries.is_empty() {\n",
            "                                let i = match self.upload_list_state.selected() {\n",
            "                                    Some(i) => if i == 0 { 0 } else { i - 1 },\n",
            "                                    None => 0,\n",
            "                                };\n",
            "                                self.upload_list_state.select(Some(i));\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Char(' ') => {\n",
            "                            if let Some(i) = self.upload_list_state.selected() {\n",
            "                                let _ = tx.try_send(AppEvent::UploadFileToggled(i));\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Char('a') => {\n",
            "                            let _ = tx.try_send(AppEvent::UploadSelectAll);\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Char('t') => {\n",
            "                            let _ = tx.try_send(AppEvent::UploadSortToggle);\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Enter => {\n",
            "                            if self.upload_sync_state.is_some() {\n",
            "                                let _ = tx.try_send(AppEvent::StartUploadRun);\n",
            "                            } else {\n",
            "                                self.active_view = ActiveView::UploadGroupSelect;\n",
            "                                self.is_loading_groups = true;\n",
            "                                self.available_groups.clear();\n",
            "                                self.group_list_state.select(Some(0));\n",
            "                                let tg = std::sync::Arc::clone(telegram);\n",
            "                                let tx_clone = tx.clone();\n",
            "                                tokio::spawn(async move {\n",
            "                                    let res = tg.get_joined_groups().await.map_err(|e| e.to_string());\n",
            "                                    let _ = tx_clone.send(AppEvent::GroupsLoaded(res)).await;\n",
            "                                });\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Esc => {\n",
            "                            self.active_view = ActiveView::UploadModeSelect;\n",
            "                        }\n",
            "                        _ => {}\n",
            "                    },\n",
            "                    ActiveView::UploadGroupSelect => match key.code {\n",
            "                        crossterm::event::KeyCode::Down | crossterm::event::KeyCode::Char('j') => {\n",
            "                            if !self.available_groups.is_empty() {\n",
            "                                let i = match self.group_list_state.selected() {\n",
            "                                    Some(i) => if i >= self.available_groups.len() - 1 { i } else { i + 1 },\n",
            "                                    None => 0,\n",
            "                                };\n",
            "                                self.group_list_state.select(Some(i));\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Up | crossterm::event::KeyCode::Char('k') => {\n",
            "                            if !self.available_groups.is_empty() {\n",
            "                                let i = match self.group_list_state.selected() {\n",
            "                                    Some(i) => if i == 0 { 0 } else { i - 1 },\n",
            "                                    None => 0,\n",
            "                                };\n",
            "                                self.group_list_state.select(Some(i));\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Esc => {\n",
            "                            self.active_view = ActiveView::UploadFileSelect;\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Enter => {\n",
            "                            if let Some(i) = self.group_list_state.selected() && let Some((id, title)) = self.available_groups.get(i) {\n",
            "                                self.upload_dest_group_id = Some(*id);\n",
            "                                self.upload_dest_group_title = title.clone();\n",
            "                                self.active_view = ActiveView::UploadTopicSelect;\n",
            "                                let tg = std::sync::Arc::clone(telegram);\n",
            "                                let tx_clone = tx.clone();\n",
            "                                let group_id = *id;\n",
            "                                tokio::spawn(async move {\n",
            "                                    let res_topics = tg.list_topics(group_id).await.map_err(|e| e.to_string());\n",
            "                                    let _ = tx_clone.send(AppEvent::TopicsLoaded(res_topics)).await;\n",
            "                                });\n",
            "                            }\n",
            "                        }\n",
            "                        _ => {}\n",
            "                    },\n",
            "                    ActiveView::UploadTopicSelect => match key.code {\n",
            "                        crossterm::event::KeyCode::Down | crossterm::event::KeyCode::Char('j') => {\n",
            "                            if !self.available_topics.is_empty() {\n",
            "                                let i = match self.topic_list_state.selected() {\n",
            "                                    Some(i) => if i >= self.available_topics.len() { i } else { i + 1 }, // Note: topics length + 1 because of manual entry option\n",
            "                                    None => 0,\n",
            "                                };\n",
            "                                self.topic_list_state.select(Some(i));\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Up | crossterm::event::KeyCode::Char('k') => {\n",
            "                            if !self.available_topics.is_empty() {\n",
            "                                let i = match self.topic_list_state.selected() {\n",
            "                                    Some(i) => if i == 0 { 0 } else { i - 1 },\n",
            "                                    None => 0,\n",
            "                                };\n",
            "                                self.topic_list_state.select(Some(i));\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Esc => {\n",
            "                            self.active_view = ActiveView::UploadGroupSelect;\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Enter => {\n",
            "                            if let Some(i) = self.topic_list_state.selected() {\n",
            "                                if i == 0 {\n",
            "                                    self.upload_topic_name_input.clear();\n",
            "                                    self.active_view = ActiveView::UploadTopicNameEntry;\n",
            "                                } else if let Some((id, title)) = self.available_topics.get(i - 1) {\n",
            "                                    self.upload_dest_topic_id = Some(*id);\n",
            "                                    self.upload_dest_topic_title = Some(title.clone());\n",
            "                                    let _ = tx.try_send(AppEvent::StartUploadRun);\n",
            "                                }\n",
            "                            }\n",
            "                        }\n",
            "                        _ => {}\n",
            "                    },\n",
            "                    ActiveView::UploadTopicNameEntry => match key.code {\n",
            "                        crossterm::event::KeyCode::Char(c) => {\n",
            "                            self.resolution_error = None;\n",
            "                            self.upload_topic_name_input.push(c);\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Backspace => {\n",
            "                            self.resolution_error = None;\n",
            "                            self.upload_topic_name_input.pop();\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Esc => {\n",
            "                            self.active_view = ActiveView::UploadTopicSelect;\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Enter => {\n",
            "                            if !self.upload_topic_name_input.is_empty() {\n",
            "                                let tg = std::sync::Arc::clone(telegram);\n",
            "                                let tx_clone = tx.clone();\n",
            "                                let group_id = self.upload_dest_group_id.unwrap();\n",
            "                                let title = self.upload_topic_name_input.clone();\n",
            "                                tokio::spawn(async move {\n",
            "                                    match tg.create_topic(group_id, &title).await {\n",
            "                                        Ok(id) => {\n",
            "                                            let _ = tx_clone.send(AppEvent::TopicCreated(id, title)).await;\n",
            "                                        }\n",
            "                                        Err(e) => {\n",
            "                                            // For now just error as topicsloaded\n",
            "                                            let _ = tx_clone.send(AppEvent::TopicsLoaded(Err(e.to_string()))).await;\n",
            "                                        }\n",
            "                                    }\n",
            "                                });\n",
            "                            }\n",
            "                        }\n",
            "                        _ => {}\n",
            "                    },\n",
            "                    ActiveView::UploadProgress => match key.code {\n",
            "                        crossterm::event::KeyCode::Char('p') | crossterm::event::KeyCode::Char(' ') => {\n",
            "                            let _ = tx.try_send(AppEvent::TogglePause);\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Esc | crossterm::event::KeyCode::Char('q') => {\n",
            "                            self.active_view = ActiveView::Home;\n",
            "                            if let Some(tx_cancel) = self.monitoring_cancel_tx.take() {\n",
            "                                let _ = tx_cancel.send(true);\n",
            "                            }\n",
            "                        }\n",
            "                        crossterm::event::KeyCode::Char('c') if key.modifiers.contains(crossterm::event::KeyModifiers::CONTROL) => {\n",
            "                            self.should_quit = true;\n",
            "                        }\n",
            "                        _ => {}\n",
            "                    },\n"
        ])
    new_lines.append(line)

with open("src/app/mod.rs", "w") as f:
    f.writelines(new_lines)
